
/**
 * AUTO-GENERATED FILE @ Wed, 20 Mar 2024 14:40:42 GMT - DO NOT EDIT!
 *
 * This file was automatically generated by schemats v.1.0.7
 * $ schemats generate postgres://username:password@localhost:5432/schemats -C -s pet_store
 *
 */

import { RandomPetFacts } from './db-custom-types'



export enum Animal {
  'Dog' = 'dog',
  'Cat' = 'cat' 
}

export interface User { 
  uuid: string
  name: string 
}

export interface Pet { 
  uuid: string
  owner?: string | null
  type: Animal
  name: string
  birthdate?: Date | null
  lastSeenLocation?: { x: number, y: number } | null
  randomFacts?: RandomPetFacts | null
  moreRandomFacts?: unknown | null
  cuteName?: string | null 
}

export interface Tables {
  user: User,
  pet: Pet
}

export type CustomTypes = RandomPetFacts